---
deployment:
  tasks:
    - /usr/bin/rsync -av --exclude=.git --exclude=node_modules . /home3/sevenpoi/nodeapps/staging_mywebsite
    - /bin/mkdir -p /home3/sevenpoi/nodeapps/staging_mywebsite/tmp
    - /bin/touch /home3/sevenpoi/nodeapps/staging_mywebsite/tmp/restart.txt