---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/sevenpoi/nodeapps/staging_mywebsite
    - echo "Forced deploy to $DEPLOYPATH" > public/deploy_log.txt
    - /bin/tar --exclude=.git --exclude=node_modules -cf - . | /bin/tar -xf - -C $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/tmp
    - /bin/touch $DEPLOYPATH/tmp/restart.txt